import { Product, Category, PricingTier } from './types';

export const CATEGORIES: Category[] = [
  { id: 'face', labelEn: 'Face Care', labelAr: 'العناية بالوجه' },
  { id: 'body', labelEn: 'Body Care', labelAr: 'العناية بالجسم' },
  { id: 'sun', labelEn: 'Sun Protection', labelAr: 'الحماية من الشمس' },
  { id: 'hair', labelEn: 'Hair & Scalp', labelAr: 'العناية بالشعر' },
];

export const PRICING_TIERS: PricingTier[] = [
  { minQty: 1, discountPercent: 0 },
  { minQty: 50, discountPercent: 0.05 },
  { minQty: 100, discountPercent: 0.10 },
  { minQty: 200, discountPercent: 0.15 },
];

// Using Unsplash images to simulate real product shots
const IMAGES = {
  serum: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=400',
  cream: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?auto=format&fit=crop&q=80&w=400',
  cleanser: 'https://images.unsplash.com/photo-1556228720-191738317769?auto=format&fit=crop&q=80&w=400',
  sun: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&q=80&w=400',
  body: 'https://images.unsplash.com/photo-1608248597279-f99d160bfbc8?auto=format&fit=crop&q=80&w=400',
  hair: 'https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?auto=format&fit=crop&q=80&w=400',
  tube: 'https://images.unsplash.com/photo-1629198688000-71f23e745b6e?auto=format&fit=crop&q=80&w=400'
};

export const PRODUCTS: Product[] = [
  {
    id: '1',
    norCode: 'NOR 100',
    nameEn: 'Iklen Perfect Sublim Serum',
    nameAr: 'سيروم إيكلين بيرفكت سوبليم',
    descriptionAr: 'سيروم مضاد للتجاعيد و البقع السوداء والكلف مصحح للون البشرة لمختلف أنواع البشرة',
    descriptionEn: 'Anti-wrinkle and dark spot serum.',
    size: '30ml',
    price: 210,
    expiryDate: '2028-03-31',
    category: 'face',
    brandLine: 'Iklen+',
    imageUrl: IMAGES.serum,
    isNew: false,
    isSor: true,
    stockLevel: 'high'
  },
  {
    id: '2',
    norCode: 'NOR 101',
    nameEn: 'UV Protect Preventative Sun Care',
    nameAr: 'واقي شمس إيكلين',
    descriptionAr: 'واقي شمس ذو فاعلية عالية للوقاية من التصبغات و محاربة التجاعيد - ضد الماء',
    descriptionEn: 'High protection sun care.',
    size: '40ml',
    price: 149.5,
    expiryDate: '2027-08-31',
    category: 'sun',
    brandLine: 'Iklen+',
    imageUrl: IMAGES.sun,
    isNew: false,
    isSor: false,
    stockLevel: 'high'
  },
  {
    id: '3',
    norCode: 'NOR 104',
    nameEn: 'Iklen Pure C Day Cream',
    nameAr: 'كريم إيكلين بيور سي النهاري',
    descriptionAr: 'كريم فيتامين سي النهاري لتفتيح البشرة و مضاد للتجاعيد والبقع الداكنة',
    descriptionEn: 'Vitamin C day cream.',
    size: '40ml',
    price: 225,
    expiryDate: '2027-09-30',
    category: 'face',
    brandLine: 'Iklen+',
    imageUrl: IMAGES.cream,
    isNew: true,
    isSor: true,
    stockLevel: 'high'
  },
  {
    id: '4',
    norCode: 'NOR 105',
    nameEn: 'Iklen Pure C Night Cream',
    nameAr: 'كريم إيكلين بيور سي الليلي',
    descriptionAr: 'كريم فيتامين سي الليلي لتفتيح البشرة و مضاد لعلامات تقدم السن والبقع الداكنة',
    descriptionEn: 'Vitamin C night cream.',
    size: '50ml',
    price: 225,
    expiryDate: '2027-06-30',
    category: 'face',
    brandLine: 'Iklen+',
    imageUrl: IMAGES.cream,
    isNew: true,
    isSor: true,
    stockLevel: 'high'
  },
  {
    id: '5',
    norCode: 'NOR 36',
    nameEn: 'Sebodiane DS Emulsion',
    nameAr: 'مستحلب سيبوديان دي إس',
    descriptionAr: 'مستحلب لتنظيم افراز الدهون فروة الرأس و علاج سريع للقشرة و الحكة مناسب لجميع الأعمار',
    descriptionEn: 'Sebum regulating emulsion.',
    size: '30ml',
    price: 64,
    expiryDate: '2029-04-30',
    category: 'face',
    brandLine: 'Sebodiane',
    imageUrl: IMAGES.tube,
    isNew: false,
    isSor: false,
    stockLevel: 'high'
  },
  {
    id: '6',
    norCode: 'NOR 35',
    nameEn: 'Sebodiane DS Anti-Dandruff Shampoo',
    nameAr: 'شامبو سيبوديان دي إس',
    descriptionAr: 'شامبو مضاد لقشرة الرأس و الجسم',
    descriptionEn: 'Anti-dandruff shampoo.',
    size: '150ml',
    price: 86,
    expiryDate: '2028-01-31',
    category: 'hair',
    brandLine: 'Sebodiane',
    imageUrl: IMAGES.hair,
    isNew: false,
    isSor: false,
    stockLevel: 'high'
  },
  {
    id: '7',
    norCode: 'NOR 32',
    nameEn: 'Kerapil Dermo-Regulating Care',
    nameAr: 'كريم كيرابيل',
    descriptionAr: 'كريم محارب للخشونة و النمو العكسي للشعر داخل الجلد',
    descriptionEn: 'Anti-ingrown hair care.',
    size: '75ml',
    price: 71.5,
    expiryDate: '2029-05-31',
    category: 'body',
    brandLine: 'Kerapil',
    imageUrl: IMAGES.tube,
    isNew: false,
    isSor: false,
    stockLevel: 'high'
  },
  {
    id: '8',
    norCode: 'NOR 95',
    nameEn: 'Bergasol B.B Light Cream SPF50+',
    nameAr: 'بيرغازول بي بي كريم',
    descriptionAr: 'واقي شمس يوفر حماية عالية جداً ضد الأشعة الضارة مع كريم أساس خفيف',
    descriptionEn: 'Tinted sun protection.',
    size: '50ml',
    price: 105.5,
    expiryDate: '2027-07-31',
    category: 'sun',
    brandLine: 'Bergasol',
    imageUrl: IMAGES.sun,
    isNew: true,
    isSor: true,
    stockLevel: 'high'
  },
  {
    id: '9',
    norCode: 'NOR 9',
    nameEn: 'Aquareva Light Moisturizing Cream',
    nameAr: 'كريم أكواريفا المرطب الخفيف',
    descriptionAr: 'كريم الترطيب الخفيف للبشرة المختلطة و الدهنية',
    descriptionEn: 'Light moisturizer.',
    size: '40ml',
    price: 67.5,
    expiryDate: '2028-04-30',
    category: 'face',
    brandLine: 'Aquareva',
    imageUrl: IMAGES.cream,
    isNew: false,
    isSor: false,
    stockLevel: 'high'
  },
  {
    id: '10',
    norCode: 'NOR 10',
    nameEn: 'Aquareva Rich Moisturizing Cream',
    nameAr: 'كريم أكواريفا الغني',
    descriptionAr: 'كريم الترطيب للبشرة شديدة الجفاف',
    descriptionEn: 'Rich moisturizer.',
    size: '40ml',
    price: 67.5,
    expiryDate: '2028-06-30',
    category: 'face',
    brandLine: 'Aquareva',
    imageUrl: IMAGES.cream,
    isNew: false,
    isSor: false,
    stockLevel: 'low'
  },
  {
    id: '11',
    norCode: 'NOR 13',
    nameEn: 'Aquareva Moisturizing Night Care',
    nameAr: 'عناية ليلية أكواريفا',
    descriptionAr: 'كريم ترطيب ليلي للوجه لجميع أنواع البشرة',
    descriptionEn: 'Night moisturizer.',
    size: '50ml',
    price: 98,
    expiryDate: '2027-11-30',
    category: 'face',
    brandLine: 'Aquareva',
    imageUrl: IMAGES.cream,
    isNew: false,
    isSor: false,
    stockLevel: 'high'
  },
  {
    id: '12',
    norCode: 'NOR 11',
    nameEn: 'Aquareva Moisturizing Serum',
    nameAr: 'سيروم أكواريفا المرطب',
    descriptionAr: 'سيروم مرطب لجميع أنواع البشرة',
    descriptionEn: 'Moisturizing serum.',
    size: '30ml',
    price: 95.5,
    expiryDate: '2028-02-29',
    category: 'face',
    brandLine: 'Aquareva',
    imageUrl: IMAGES.serum,
    isNew: false,
    isSor: false,
    stockLevel: 'high'
  },
  {
    id: '13',
    norCode: 'NOR 15',
    nameEn: 'Aquareva Lip Balm',
    nameAr: 'مرطب شفاه أكواريفا',
    descriptionAr: 'مرطب شفاه',
    descriptionEn: 'Lip balm.',
    size: '4g',
    price: 35,
    expiryDate: '2027-11-30',
    category: 'face',
    brandLine: 'Aquareva',
    imageUrl: IMAGES.tube,
    isNew: false,
    isSor: false,
    stockLevel: 'high'
  },
  {
    id: '14',
    norCode: 'NOR 16',
    nameEn: 'Aquareva Repairing Hand Cream',
    nameAr: 'كريم اليدين أكواريفا',
    descriptionAr: 'كريم مرطب لليدين واصلاح اعراض الجفاف',
    descriptionEn: 'Hand cream.',
    size: '50ml',
    price: 47,
    expiryDate: '2027-11-30',
    category: 'body',
    brandLine: 'Aquareva',
    imageUrl: IMAGES.tube,
    isNew: false,
    isSor: false,
    stockLevel: 'high'
  },
  {
    id: '15',
    norCode: 'NOR 18',
    nameEn: 'Aquareva Moisturizing Body Milk',
    nameAr: 'حليب الجسم أكواريفا',
    descriptionAr: 'كريم ترطيب للجسم',
    descriptionEn: 'Body milk.',
    size: '400ml',
    price: 115,
    expiryDate: '2029-03-31',
    category: 'body',
    brandLine: 'Aquareva',
    imageUrl: IMAGES.body,
    isNew: false,
    isSor: false,
    stockLevel: 'high'
  },
  {
    id: '16',
    norCode: 'NOR 21',
    nameEn: 'Xerodiane AP+ Gentle Foaming Gel',
    nameAr: 'جل رغوي زيروديان',
    descriptionAr: 'غسول جل رغوي لطيف للوجه و الجسم',
    descriptionEn: 'Gentle foaming gel.',
    size: '1L',
    price: 107,
    expiryDate: '2029-04-30',
    category: 'body',
    brandLine: 'Xerodiane',
    imageUrl: IMAGES.cleanser,
    isNew: false,
    isSor: false,
    stockLevel: 'high'
  },
  {
    id: '17',
    norCode: 'NOR 22',
    nameEn: 'Xerodiane AP+ Emollient Cream',
    nameAr: 'كريم زيروديان المرطب',
    descriptionAr: 'كريم مرطب و مهدئ بمفعول مضاد للجفاف للوجه و الجسم',
    descriptionEn: 'Emollient cream.',
    size: '200ml',
    price: 90,
    expiryDate: '2028-03-31',
    category: 'body',
    brandLine: 'Xerodiane',
    imageUrl: IMAGES.cream,
    isNew: false,
    isSor: false,
    stockLevel: 'high'
  },
  {
    id: '18',
    norCode: 'NOR 86',
    nameEn: 'Cicadiane Cream',
    nameAr: 'كريم سيكاديان',
    descriptionAr: 'كريم لتحفيز شفاء الندوب و الجروح بفاعلية مرطبة و ملطفة للبشرة',
    descriptionEn: 'Repairing cream.',
    size: '40ml',
    price: 65.5,
    expiryDate: '2029-03-31',
    category: 'face',
    brandLine: 'Cicadiane',
    imageUrl: IMAGES.tube,
    isNew: false,
    isSor: false,
    stockLevel: 'high'
  },
  {
    id: '19',
    norCode: 'NOR 90',
    nameEn: 'Cicadiane SPF 50+ Cream',
    nameAr: 'كريم سيكاديان واقي شمس',
    descriptionAr: 'واقي شمس بحماية عالية محفزة لشفاء الجروح و الندوب',
    descriptionEn: 'Repairing sun cream.',
    size: '40ml',
    price: 85,
    expiryDate: '2027-07-31',
    category: 'face',
    brandLine: 'Cicadiane',
    imageUrl: IMAGES.sun,
    isNew: false,
    isSor: true,
    stockLevel: 'high'
  },
  {
    id: '20',
    norCode: 'NOR 89',
    nameEn: 'Cicadiane Lotion',
    nameAr: 'لوشن سيكاديان',
    descriptionAr: 'لوشن سيكا مرمم للبشرة مناسب للأماكن الرطبة والتهابات الحفاضات',
    descriptionEn: 'Repairing lotion.',
    size: '100ml',
    price: 94.5,
    expiryDate: '2027-11-30',
    category: 'body',
    brandLine: 'Cicadiane',
    imageUrl: IMAGES.tube,
    isNew: false,
    isSor: false,
    stockLevel: 'high'
  },
  {
    id: '21',
    norCode: 'NOR 72',
    nameEn: 'Trio A Intensive Depigmenting Care',
    nameAr: 'تريو أ مكثف',
    descriptionAr: 'كريم تفتيح مكثف لمنع وعلاج التصبغات والبقع الغامقة',
    descriptionEn: 'Depigmenting care.',
    size: '30ml',
    price: 95,
    expiryDate: '2028-05-31',
    category: 'face',
    brandLine: 'Trio',
    imageUrl: IMAGES.tube,
    isNew: false,
    isSor: false,
    stockLevel: 'high'
  },
  {
    id: '22',
    norCode: 'NOR 73',
    nameEn: 'Trio D Depigmenting Care',
    nameAr: 'تريو د',
    descriptionAr: 'كريم تفتيح و مزيل التصبغات وموحد للون البشرة',
    descriptionEn: 'Depigmenting and unifying care.',
    size: '30ml',
    price: 115,
    expiryDate: '2028-01-31',
    category: 'face',
    brandLine: 'Trio',
    imageUrl: IMAGES.tube,
    isNew: false,
    isSor: false,
    stockLevel: 'high'
  },
  {
    id: '23',
    norCode: 'NOR 67',
    nameEn: 'Trio White XP Serum',
    nameAr: 'سيروم تريو وايت إكس بي',
    descriptionAr: 'سيروم تفتيح و توحيد لون البشرة و التصبغات والبقع الغامقة',
    descriptionEn: 'Anti-dark spot serum.',
    size: '30ml',
    price: 138,
    expiryDate: '2027-09-30',
    category: 'face',
    brandLine: 'Trio White',
    imageUrl: IMAGES.serum,
    isNew: true,
    isSor: true,
    stockLevel: 'high'
  },
  {
    id: '24',
    norCode: 'NOR 71 AA',
    nameEn: 'Trio White XP Body Lotion',
    nameAr: 'لوشن تريو وايت إكس بي',
    descriptionAr: 'لوشن تفتيح الجسم يعمل على إزالة وتوحيد لون البشرة',
    descriptionEn: 'Lightening body lotion.',
    size: '400ml',
    price: 188.5,
    expiryDate: '2028-10-31',
    category: 'body',
    brandLine: 'Trio White',
    imageUrl: IMAGES.body,
    isNew: true,
    isSor: true,
    stockLevel: 'high'
  },
  {
    id: '25',
    norCode: 'NOR 39',
    nameEn: 'Exfoliac Gentle Foaming Gel',
    nameAr: 'جل رغوي إكسفولياك',
    descriptionAr: 'غسول جل رغوي لطيف منظف للبشرة و متحكم في إفراز الدهون',
    descriptionEn: 'Gentle foaming gel.',
    size: '200ml',
    price: 75,
    expiryDate: '2028-08-31',
    category: 'face',
    brandLine: 'Exfoliac',
    imageUrl: IMAGES.cleanser,
    isNew: false,
    isSor: false,
    stockLevel: 'high'
  },
  {
    id: '26',
    norCode: 'NOR 47',
    nameEn: 'Exfoliac Matifying Suncare Fluid SPF 50+',
    nameAr: 'واقي شمس إكسفولياك',
    descriptionAr: 'واقي شمس بحماية عالية للبشرة الدهنية والتي تعاني من حب الشباب',
    descriptionEn: 'Matifying suncare fluid.',
    size: '40ml',
    price: 87.5,
    expiryDate: '2028-05-31',
    category: 'sun',
    brandLine: 'Exfoliac',
    imageUrl: IMAGES.sun,
    isNew: false,
    isSor: true,
    stockLevel: 'high'
  },
  {
    id: '27',
    norCode: 'NOR 124',
    nameEn: 'Exfoliac Purifying Micellar Water',
    nameAr: 'ماء ميسيلار إكسفولياك',
    descriptionAr: 'ماء ميسيلار لتنظيف البشرة وإزالة المكياج',
    descriptionEn: 'Purifying micellar water.',
    size: '200ml',
    price: 88,
    expiryDate: '2027-08-01',
    category: 'face',
    brandLine: 'Exfoliac',
    imageUrl: IMAGES.cleanser,
    isNew: false,
    isSor: false,
    stockLevel: 'high'
  },
  {
    id: '28',
    norCode: 'NOR 40',
    nameEn: 'Exfoliac Intensive Foaming Gel',
    nameAr: 'جل رغوي مكثف إكسفولياك',
    descriptionAr: 'غسول جل رغوي مكثف منظف للبشرة و متحكم في إفراز الدهون',
    descriptionEn: 'Intensive foaming gel.',
    size: '200ml',
    price: 85,
    expiryDate: '2028-01-31',
    category: 'face',
    brandLine: 'Exfoliac',
    imageUrl: IMAGES.cleanser,
    isNew: false,
    isSor: false,
    stockLevel: 'high'
  },
  {
    id: '29',
    norCode: 'NOR 42',
    nameEn: 'Exfoliac Purifying Mask',
    nameAr: 'قناع إكسفولياك المنقي',
    descriptionAr: 'قناع تنقية للبشرة يعمل على تضيق المسامات ويقلل إفراز الدهون',
    descriptionEn: 'Purifying mask.',
    size: '50ml',
    price: 62,
    expiryDate: '2027-06-30',
    category: 'face',
    brandLine: 'Exfoliac',
    imageUrl: IMAGES.tube,
    isNew: false,
    isSor: false,
    stockLevel: 'high'
  },
  // TEST PRODUCTS - EDGE CASES
  {
    id: 'test-1',
    norCode: 'TEST 001',
    nameEn: 'Test Critical Expiry Item',
    nameAr: 'منتج تجريبي - صلاحية وشيكة',
    descriptionAr: 'هذا المنتج لاختبار حالة الصلاحية الحرجة (أقل من 6 أشهر) - يظهر باللون الأحمر',
    descriptionEn: 'Testing critical expiry date (< 6 months).',
    size: '50ml',
    price: 50,
    expiryDate: '2025-06-15', // Approx 4 months from now (assuming 2025 context or typical current date, will verify relative to 'today' in utils)
    category: 'face',
    brandLine: 'TestLine',
    imageUrl: IMAGES.cream,
    isNew: false,
    isSor: false,
    stockLevel: 'high'
  },
  {
    id: 'test-2',
    norCode: 'TEST 002',
    nameEn: 'Test Low Stock Item',
    nameAr: 'منتج تجريبي - مخزون منخفض',
    descriptionAr: 'هذا المنتج لاختبار حالة المخزون المنخفض - يظهر تنبيه بأن الكمية محدودة',
    descriptionEn: 'Testing low stock indicator.',
    size: '100ml',
    price: 120,
    expiryDate: '2028-01-01',
    category: 'body',
    brandLine: 'TestLine',
    imageUrl: IMAGES.body,
    isNew: false,
    isSor: false,
    stockLevel: 'low'
  },
  {
    id: 'test-3',
    norCode: 'TEST 003',
    nameEn: 'Test Sold Out Item',
    nameAr: 'منتج تجريبي - نفذت الكمية',
    descriptionAr: 'هذا المنتج لاختبار حالة نفاذ الكمية - يظهر باللون الرمادي مع ختم نفاذ الكمية',
    descriptionEn: 'Testing sold out status.',
    size: '200ml',
    price: 85,
    expiryDate: '2027-12-31',
    category: 'hair',
    brandLine: 'TestLine',
    imageUrl: IMAGES.hair,
    isNew: false,
    isSor: false,
    stockLevel: 'out'
  },
  {
    id: 'test-4',
    norCode: 'TEST 004',
    nameEn: 'Test Warning Expiry Item',
    nameAr: 'منتج تجريبي - صلاحية متوسطة',
    descriptionAr: 'هذا المنتج لاختبار حالة الصلاحية المتوسطة (بين 6 و 12 شهر) - يظهر باللون الأصفر',
    descriptionEn: 'Testing warning expiry date (9 months).',
    size: '30ml',
    price: 200,
    expiryDate: '2025-11-30', // Approx 9 months
    category: 'face',
    brandLine: 'TestLine',
    imageUrl: IMAGES.serum,
    isNew: false,
    isSor: true,
    stockLevel: 'high'
  }
];